services:
  - type: web
    name: flask-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      chmod +x backend/startup.sh
      ./backend/startup.sh
    startCommand: "gunicorn app:app --chdir backend"
    repo: https://github.com/AyushKatre05/MCQ-ML-Backend.git
    branch: main
    directory: backend
